language: node_js
node_js:
  - 8
  - 10
  - 12
os:
  - linux
  - osx
  - windows
before_script:
  - npm install -g gulp-cli

jobs:
  include:
    - os: linux
      script:
        - npm run build
        - npm test
    - os: osx
      script:
        - npm run build
    - os: windows
      script:
        - npm run build