language: node_js
node_js:
  - 8
  - 10
  - 12
os:
  - linux
  - osx
  - windows
before_script:
  - npm install -g gulp-cli

jobs:
  include:
    - os: linux
      node_js: 
        - 8
        - 10
        - 12
      script:
        - npm run build
        - npm test

    - os: osx
      node_js: 
        - 8
        - 10
        - 12
      script:
        - npm run build

    - os: windows
      node_js: 
        - 8
        - 10
        - 12
      script:
        - npm run build
