language: node_js
node_js:
  - 8
  - 10
  - 12
os:
  - linux
  - osx
  - windows
before_script:
  - npm install -g gulp-cli

jobs:
  exclude:
    - os: osx
      node_js: 8
      script: npm test

script:
  - npm run build
  - npm test
