name: CI Pipeline

on:
    push:
        branches: [main]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 24
                # cache: "npm"          # enables only if lock file exists
            
            - name: Install dependencies
              run: npm install

            - name: Build Package
              run: npm run build:gh

            - name: Run Tests
              run: npm test:gh

            - name: Bump version
              run: | 
                npm version patch -m "release: %s"

            - name: Push Tag
              run: |
                git push origin main --follow-tags

            - name: Publish to npm
              run: npm publish --access public --no-git-shecks
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}